<?php

/**
 * @file
 * Contains zucar_rest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function my_api_rest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zucar_rest module.
    case 'help.page.my_api_rest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Rest Api for your App') . '</p>';
      return $output;

    default:
  }
}
